import { Badge } from "@/components/ui/badge"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"

// Generated page sections
export function Hero() {
  return (
    <section id={"hero"} className={"py-12 sm:py-16 lg:py-20"}>
      <div className="container mx-auto px-4 sm:px-6">
        <div className={"flex flex-col items-center text-center max-w-4xl mx-auto"}>
<badge variant="secondary" className="mb-4">Welcome</badge>
<label className="text-4xl font-bold tracking-tight">Build Something Great</label>
<label className="text-lg text-muted-foreground mt-4 max-w-2xl">A beautiful, production-ready site generated by AI.</label>
<button size="lg" className="mt-8">Get Started</button>
        </div>
      </div>
    </section>
  )
}

export const metadata = {
  title: "Home",
  description: "phone shop",
}

export default function Page() {
  return (
    <>
      <Hero />
    </>
  )
}
